// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi-pFXcjM3ZmztSyZLCfpb1v3ZJkQEmm0',
    appId: '1:775025713895:web:2c51a54386084a8a3ef842',
    messagingSenderId: '775025713895',
    projectId: 'chatty-fc08b',
    authDomain: 'chatty-fc08b.firebaseapp.com',
    storageBucket: 'chatty-fc08b.appspot.com',
    measurementId: 'G-2T4QSLRVQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZE-5ltRnIQCY6l-SR1gKLoXERxgqAcWY',
    appId: '1:775025713895:android:d9f89bc6ef6a6b663ef842',
    messagingSenderId: '775025713895',
    projectId: 'chatty-fc08b',
    storageBucket: 'chatty-fc08b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm5X714LImIbWFHaZsFcjLqT0Tkx9mxe0',
    appId: '1:775025713895:ios:768fcd75f9524d603ef842',
    messagingSenderId: '775025713895',
    projectId: 'chatty-fc08b',
    storageBucket: 'chatty-fc08b.appspot.com',
    androidClientId: '775025713895-ejc3fuk8n3v9fjgn7p4cppnd6o51i1er.apps.googleusercontent.com',
    iosClientId: '775025713895-bjj5bth9oit44qc08h2u6967i3lo851e.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
